=== BackupTheBerlios/rmframework-svn/base/trunk/RMxmlHelper/src/main/resources/schema/serverConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://xml.form105.net/schema/model"
	elementFormDefault="qualified" xmlns:rm="http://xml.form105.net/schema/model">

	<xsd:element name="serverConfig">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="inbound" maxOccurs="unbounded">
					<xsd:complexType mixed="true">
						<xsd:sequence>
							<xsd:element name="id" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="alias" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="host" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="port" maxOccurs="1" minOccurs="1" type="xsd:int"></xsd:element>
							<xsd:element name="type" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="sizePendingQueue" maxOccurs="1" minOccurs="0" type="xsd:int"></xsd:element>
							<xsd:element name="validatorKey" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="packetSize" maxOccurs="1" minOccurs="1" type="xsd:int"></xsd:element>
							<xsd:element name="contentIdentifier" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="content">
		<xsd:complexType>
			<xsd:sequence>
				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== BackupTheBerlios/rmframework-svn/base/trunk/RMxmlHelper/xml/serverConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<rm:serverConfig xmlns:rm="http://xml.form105.net/schema/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.form105.net/schema/model ../src/main/resources/schema/serverConfig.xsd ">
  <rm:inbound>
    <rm:id>rm:id</rm:id>
    <rm:alias>rm:alias</rm:alias>
    <rm:host>localhost</rm:host>
    <rm:port>0</rm:port>
    <rm:type/>
    <rm:validatorKey>kaiserValidator</rm:validatorKey>
    <rm:packetSize>132</rm:packetSize>
    <rm:contentIdentifier>kaiserContentIdentifier</rm:contentIdentifier>
  </rm:inbound>
</rm:serverConfig>
