=== BackupTheBerlios/rmframework-svn/base/trunk/RMBase/target/generated-classes/xmlbeans/schemaorg_apache_xmlbeans/src/serverConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xml.form105.net/schema/model"
	elementFormDefault="qualified" xmlns="http://xml.form105.net/schema/model">

	<xsd:element name="connectionPool">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="inbound" maxOccurs="unbounded">
					
					<xsd:complexType mixed="true">
						
						<xsd:sequence>
							<xsd:group ref="connectionDefaults"></xsd:group>

							<xsd:element name="sizePendingQueue" maxOccurs="1" minOccurs="0" type="xsd:int"></xsd:element>
							<xsd:element name="validatorKey" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
							<xsd:element name="packetSize" maxOccurs="1" minOccurs="1" type="xsd:int"></xsd:element>
							<xsd:element name="contentIdentifier" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="outbound" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:group ref="connectionDefaults"></xsd:group>
						
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:group name="connectionDefaults">
		<xsd:sequence>
		<xsd:element name="id" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
		<xsd:element name="alias" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
		<xsd:element name="host" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
		<xsd:element name="port" maxOccurs="1" minOccurs="1" type="xsd:int"></xsd:element>
		<xsd:element name="type" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:group>

</xsd:schema>

=== BackupTheBerlios/rmframework-svn/base/trunk/RMBase/config/serverConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- connectionPool xmlns="http://xml.form105.net/schema/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.form105.net/schema/model ../../RMxmlHelper/src/main/resources/schema/serverConfig.xsd "-->
<connectionPool>
  <inbound>
    <id>plc01</id>
    <alias>input_server_plc_01</alias>
    <host>192.168.1.30</host>
    <port>50005</port>
    <type>inbound</type>
    <sizePendingQueue>2</sizePendingQueue>
    <!-- this is the key used for pico container -->
    <validatorKey>kaiserValidator</validatorKey>
    <packetSize>132</packetSize>
    <contentIdentifier>kaiserContentIdentifier</contentIdentifier>
  </inbound>
  <outbound>
  	<id>jdbcFileMaker</id>
  	<alias>fmJdbc01</alias>
  	<host>localhost</host>
  	<port>todo</port>
  	<type>jdbc</type>
  	<parameters>
  		<parameter key="tablespace">myTablespace</parameter>
  	</parameters>
  </outbound>
</connectionPool>
